export const productConstants = {

    GETALL_REQUEST: 'PRODUCTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PRODUCTS_GETALL_FAILURE',

    QUANTITY_CHANGE_REQUEST: 'PRODUCTS_QUANTITY_CHANGE_REQUEST',
    QUANTITY_CHANGE_SUCCESS: 'PRODUCTS_QUANTITY_CHANGE_SUCCESS',
    QUANTITY_CHANGE_FAILURE: 'PRODUCTS_QUANTITY_CHANGE_FAILURE',

    ADDED_REQUEST: 'PRODUCTS_ADDED_REQUEST',
    ADDED_SUCCESS: 'PRODUCTS_ADDED_SUCCESS',
    ADDED_FAILURE: 'PRODUCTS_QUANTITY_CHANGE_FAILURE',

    DELETE_CHANGE_REQUEST:'PRODUCT_DELETE_REQUEST',
    DELETE_CHANGE_SUCCESS:'PRODUCT_DELETE_SUCCESS',
    DELETE_CHANGE_FAILURE:'PRODUCT_DELETE_FAILURE'

};